# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df72ddaa25837792710a72de73b846ec01385cb34b4aaec57ab8933db12fd72b702e5fec4e9d93267ffca823a3ac33b28889e1625da13e1d2e3c3e3102a1cd56

test:
  secret_key_base: c49bad05dc63b41b45a45b47486172799282a50d21d767b7cb6b419666709a2ebb3121fcd572373ea0364cdf7680e7565ee1dc09b5ed96f2896e564ab9dcf4d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
